### ISSUE TITLE
How to get an image represent from an inertial or skeleton data sequence

### ISSUE THREAD

**Issue by NeonLix** [raphaelmemmesheimer/sl-dml#3]
I've read your paper and code and would like to train and test under other datasets, but can't seem to get image representations. I hope you can provide the source code or describe in detail how to do it. Much appreciated!

**Comment by raphaelmemmesheimer** [comment]
That's a good point. I just added a tiny script for a skeleton sample from the UTD-MHAD dataset in `representation/`. For other datasets, ideally multivariate sequences with three components per signal, it should work analog. I'll add the complete code for generating the used datasets later, but the core is in there.

**Comment by NeonLix** [comment]
thanks!
