### ISSUE TITLE
hydra-core and omegaconf version

### ISSUE THREAD

**Issue by EdwardTse9944** [raphaelmemmesheimer/sl-dml#4]
Hi, thank you so much for your outstanding research work. would you please tell me about the specific version of hydra-core and omegaconf?

many thanks

**Comment by rlleshi** [comment]
`hydra-core 0.11.3`
`omegaconf 1.4.1`

**Comment by EdwardTse9944** [comment]
> `hydra-core 0.11.3` `omegaconf 1.4.1`

hi, thanks for your kindly answer. I am trying to reproduce this work but meet the following error, would you please  have a look if it is possible?

> Data dir: /home/campus.ncl.ac.uk/b7000659/PycharmProjects/skl-dml/skeleton-dml/data/ntu/ntu_swap_axes_testswapaxes/one_shot
final_train
Trainset:  94819 Testset:  18906 Samplesset:  20
NTU_ONE_SHOT_SWAP_AXIS_model_resnet18_cl_cross_entropy_ml_triplet_margin_miner_multi_similarity_mix_ml_0.50_mix_cl_0.50_resize_256_emb_size_128_class_size_21_opt_rmsprop_lr_0.00_
[2022-09-11 12:18:18,047][root][INFO] - Initializing dataloader
[2022-09-11 12:18:18,048][root][INFO] - Initializing dataloader iterator
[2022-09-11 12:18:19,644][root][INFO] - Done creating dataloader iterator
[2022-09-11 12:18:19,646][root][INFO] - TRAINING EPOCH 1
  0%|                                                                                                                                               | 0/2962 [00:00<?, ?it/s]/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [1,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [2,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [3,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [4,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [5,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [6,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [7,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [8,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [9,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [10,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [11,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [12,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [13,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [14,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [15,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [16,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [17,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [18,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [19,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [20,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [21,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [22,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [23,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [24,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [25,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [26,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [27,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [28,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [29,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [30,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [31,0,0] Assertion `t >= 0 && t < n_classes` failed.

RuntimeError: copy_if failed to synchronize: cudaErrorAssert: device-side assert triggered

I am not sure if it is due to the range of the label or any other error?
Thanks for your help.

**Comment by EdwardTse9944** [comment]
> `hydra-core 0.11.3` `omegaconf 1.4.1`

by the way, I am not quite sure if this error is due to the version of the package, would you please share with me the detailed version of all the packages if you have successfully reproduced this work? thank you so much

**Comment by rlleshi** [comment]
This error is not related to package versions.

`Assertion t >= 0 && t < n_classes failed` is basically saying that you have a discrepancy in the number of classes of the classifier's head and the number of classes that the dataset has. You should make sure that your dataset config is properly set. 

e.g. 
```
dataset:
  name: "NTU_ONE_SHOT_SWAP_AXIS"
  data_dir: "/ntu/ntu_swap_axes_testswapaxes/one_shot"
  train_classes: 100
```
You should make sure that you really have 100 train classes in the `/ntu/ntu_swap_axes_testswapaxes/one_shot` dir. If you have 101 then the following error is thrown since you are trying to construct a classifier with 100 classes when in reality there are 101.

**Comment by EdwardTse9944** [comment]
> This error is not related to package versions.
> 
> `Assertion t >= 0 && t < n_classes failed` is basically saying that you have a discrepancy in the number of classes of the classifier's head and the number of classes that the dataset has. You should make sure that your dataset config is properly set.
> 
> e.g.
> 
> ```
> dataset:
>   name: "NTU_ONE_SHOT_SWAP_AXIS"
>   data_dir: "/ntu/ntu_swap_axes_testswapaxes/one_shot"
>   train_classes: 100
> ```
> 
> You should make sure that you really have 100 train classes in the `/ntu/ntu_swap_axes_testswapaxes/one_shot` dir. If you have 101 then the following error is thrown since you are trying to construct a classifier with 100 classes when in reality there are 101.

Thanks for your response. When I try to downgrade the record-keeper version to 0.9.24. The error is fixed.

**Comment by raphaelmemmesheimer** [comment]
> `hydra-core 0.11.3` `omegaconf 1.4.1`

Thanks for pointing out. I'll add the version numbers to the `requirements.txt`.
